import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Illumination, MakeTime, MoonPhase } from 'astronomy-engine';

type PhaseName =
  | 'New Moon'
  | 'Waxing Crescent'
  | 'First Quarter'
  | 'Waxing Gibbous'
  | 'Full Moon'
  | 'Waning Gibbous'
  | 'Last Quarter'
  | 'Waning Crescent';

interface MoonPhaseEntry {
  date: string;
  illumination: number;
  phase: PhaseName;
  phaseAngle: number;
  image: string | null;
  svsFrame: number;
}

const ANNIVERSARY = { year: 2024, month: 3, day: 6 };

// NASA SVS publishes a new "Dial-A-Moon" page each year with a different ID.
// Add the new year's ID here every January (find via https://svs.gsfc.nasa.gov/).
const SVS_PAGE_BY_YEAR: Record<number, number> = {
  2024: 5187,
  2025: 5415,
  2026: 5587,
};

const SVS_SIZE = '216x216_1x1_30p';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT = resolve(__dirname, '..');
const IMAGE_DIR = resolve(PROJECT, 'public/images/moon-phases');
const DATA_FILE = resolve(PROJECT, 'src/data/moon-phases.ts');

function hourOfYearUTC(d: Date): number {
  const yearStart = Date.UTC(d.getUTCFullYear(), 0, 1, 0, 0, 0);
  return Math.floor((d.getTime() - yearStart) / 3_600_000) + 1;
}

function svsUrlFor(date: Date): string {
  const year = date.getUTCFullYear();
  const id = SVS_PAGE_BY_YEAR[year];
  if (!id) {
    throw new Error(
      `No SVS page ID configured for year ${year}. Look up the new ID at https://svs.gsfc.nasa.gov/ and add it to SVS_PAGE_BY_YEAR.`
    );
  }
  const bucket = String(Math.floor(id / 100) * 100).padStart(6, '0');
  const idStr = String(id).padStart(6, '0');
  const frame = String(hourOfYearUTC(date)).padStart(4, '0');
  return `https://svs.gsfc.nasa.gov/vis/a000000/a${bucket}/a${idStr}/frames/${SVS_SIZE}/moon.${frame}.jpg`;
}

function phaseName(angleDeg: number): PhaseName {
  const a = ((angleDeg % 360) + 360) % 360;
  if (a < 5 || a >= 355) return 'New Moon';
  if (Math.abs(a - 90) < 5) return 'First Quarter';
  if (Math.abs(a - 180) < 5) return 'Full Moon';
  if (Math.abs(a - 270) < 5) return 'Last Quarter';
  if (a < 90) return 'Waxing Crescent';
  if (a < 180) return 'Waxing Gibbous';
  if (a < 270) return 'Waning Gibbous';
  return 'Waning Crescent';
}

function isoDate(d: Date): string {
  return d.toISOString().slice(0, 10);
}

function listMonatstage(now: Date): Date[] {
  const dates: Date[] = [];
  let cursor = new Date(
    Date.UTC(ANNIVERSARY.year, ANNIVERSARY.month - 1, ANNIVERSARY.day, 12)
  );
  while (cursor.getTime() <= now.getTime()) {
    dates.push(new Date(cursor));
    cursor = new Date(
      Date.UTC(
        cursor.getUTCFullYear(),
        cursor.getUTCMonth() + 1,
        ANNIVERSARY.day,
        12
      )
    );
  }
  return dates;
}

async function downloadIfMissing(url: string, dest: string): Promise<boolean> {
  if (existsSync(dest)) return true;
  try {
    const res = await fetch(url);
    if (!res.ok) {
      console.warn(`  warn: HTTP ${res.status} for ${url}`);
      return false;
    }
    const buf = Buffer.from(await res.arrayBuffer());
    mkdirSync(dirname(dest), { recursive: true });
    writeFileSync(dest, buf);
    console.log(`  downloaded ${dest.split('/').slice(-2).join('/')}`);
    return true;
  } catch (err) {
    console.warn(`  warn: download failed for ${url}: ${(err as Error).message}`);
    return false;
  }
}

function renderDataFile(rows: MoonPhaseEntry[]): string {
  const header =
    `// Generated by scripts/generate-moon-phases.ts — DO NOT EDIT BY HAND\n` +
    `// Run \`npm run moon\` to regenerate.\n\n`;

  const types =
    `export type PhaseName =\n` +
    `  | 'New Moon'\n` +
    `  | 'Waxing Crescent'\n` +
    `  | 'First Quarter'\n` +
    `  | 'Waxing Gibbous'\n` +
    `  | 'Full Moon'\n` +
    `  | 'Waning Gibbous'\n` +
    `  | 'Last Quarter'\n` +
    `  | 'Waning Crescent';\n\n` +
    `export interface MoonPhase {\n` +
    `  date: string;\n` +
    `  illumination: number;\n` +
    `  phase: PhaseName;\n` +
    `  phaseAngle: number;\n` +
    `  image: string | null;\n` +
    `  svsFrame: number;\n` +
    `}\n\n`;

  const items = rows
    .map(
      (r) =>
        `  {\n` +
        `    date: '${r.date}',\n` +
        `    illumination: ${r.illumination},\n` +
        `    phase: '${r.phase}',\n` +
        `    phaseAngle: ${r.phaseAngle},\n` +
        `    image: ${r.image === null ? 'null' : `'${r.image}'`},\n` +
        `    svsFrame: ${r.svsFrame},\n` +
        `  },`
    )
    .join('\n');

  return `${header}${types}export const moonPhases: MoonPhase[] = [\n${items}\n];\n`;
}

async function main() {
  mkdirSync(IMAGE_DIR, { recursive: true });
  const now = new Date();
  const dates = listMonatstage(now);
  console.log(`Found ${dates.length} Monatstage from ${isoDate(dates[0])} to ${isoDate(dates[dates.length - 1])}.`);

  const rows: MoonPhaseEntry[] = [];
  let downloadFailures = 0;

  for (const d of dates) {
    const iso = isoDate(d);
    const localFile = resolve(IMAGE_DIR, `${iso}.jpg`);
    const imagePath = `/images/moon-phases/${iso}.jpg`;

    let url: string | null = null;
    try {
      url = svsUrlFor(d);
    } catch (err) {
      console.warn(`  skip download for ${iso}: ${(err as Error).message}`);
    }

    let imageAvailable = existsSync(localFile);
    if (!imageAvailable && url !== null) {
      const ok = await downloadIfMissing(url, localFile);
      imageAvailable = ok || existsSync(localFile);
      if (!imageAvailable) downloadFailures++;
    }

    const t = MakeTime(d);
    const angle = MoonPhase(t);
    const illum = Illumination('Moon', t);

    rows.push({
      date: iso,
      illumination: Math.round(illum.phase_fraction * 1000) / 10,
      phase: phaseName(angle),
      phaseAngle: Math.round(angle * 100) / 100,
      image: imageAvailable ? imagePath : null,
      svsFrame: hourOfYearUTC(d),
    });
  }

  rows.sort((a, b) => a.date.localeCompare(b.date));
  writeFileSync(DATA_FILE, renderDataFile(rows));
  console.log(`Wrote ${rows.length} entries to ${DATA_FILE}.`);

  if (downloadFailures > 0) {
    console.warn(
      `\n${downloadFailures} image(s) could not be downloaded — entries will use the SVG fallback. ` +
        `Re-run \`npm run moon\` once NASA SVS is reachable to fill them in.`
    );
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
