// Generated by scripts/generate-moon-phases.ts — DO NOT EDIT BY HAND
// Run `npm run moon` to regenerate.

export type PhaseName =
  | 'New Moon'
  | 'Waxing Crescent'
  | 'First Quarter'
  | 'Waxing Gibbous'
  | 'Full Moon'
  | 'Waning Gibbous'
  | 'Last Quarter'
  | 'Waning Crescent';

export interface MoonPhase {
  date: string;
  illumination: number;
  phase: PhaseName;
  phaseAngle: number;
  image: string | null;
  svsFrame: number;
}

export const moonPhases: MoonPhase[] = [
  {
    date: '2024-03-06',
    illumination: 20.8,
    phase: 'Waning Crescent',
    phaseAngle: 306.01,
    image: null,
    svsFrame: 1573,
  },
  {
    date: '2024-04-06',
    illumination: 7.6,
    phase: 'Waning Crescent',
    phaseAngle: 328.16,
    image: null,
    svsFrame: 2317,
  },
  {
    date: '2024-05-06',
    illumination: 3.8,
    phase: 'Waning Crescent',
    phaseAngle: 337.61,
    image: null,
    svsFrame: 3037,
  },
  {
    date: '2024-06-06',
    illumination: 0.2,
    phase: 'New Moon',
    phaseAngle: 359.66,
    image: null,
    svsFrame: 3781,
  },
  {
    date: '2024-07-06',
    illumination: 0.5,
    phase: 'Waxing Crescent',
    phaseAngle: 6.55,
    image: null,
    svsFrame: 4501,
  },
  {
    date: '2024-08-06',
    illumination: 4,
    phase: 'Waxing Crescent',
    phaseAngle: 22.9,
    image: null,
    svsFrame: 5245,
  },
  {
    date: '2024-09-06',
    illumination: 10.2,
    phase: 'Waxing Crescent',
    phaseAngle: 37.11,
    image: null,
    svsFrame: 5989,
  },
  {
    date: '2024-10-06',
    illumination: 12.1,
    phase: 'Waxing Crescent',
    phaseAngle: 40.44,
    image: null,
    svsFrame: 6709,
  },
  {
    date: '2024-11-06',
    illumination: 22.6,
    phase: 'Waxing Crescent',
    phaseAngle: 56.43,
    image: null,
    svsFrame: 7453,
  },
  {
    date: '2024-12-06',
    illumination: 27.3,
    phase: 'Waxing Crescent',
    phaseAngle: 62.78,
    image: null,
    svsFrame: 8173,
  },
  {
    date: '2025-01-06',
    illumination: 44.5,
    phase: 'Waxing Crescent',
    phaseAngle: 83.5,
    image: null,
    svsFrame: 133,
  },
  {
    date: '2025-02-06',
    illumination: 63.1,
    phase: 'Waxing Gibbous',
    phaseAngle: 105.1,
    image: null,
    svsFrame: 877,
  },
  {
    date: '2025-03-06',
    illumination: 48,
    phase: 'First Quarter',
    phaseAngle: 87.57,
    image: null,
    svsFrame: 1549,
  },
  {
    date: '2025-04-06',
    illumination: 64.7,
    phase: 'Waxing Gibbous',
    phaseAngle: 107.06,
    image: null,
    svsFrame: 2293,
  },
  {
    date: '2025-05-06',
    illumination: 69,
    phase: 'Waxing Gibbous',
    phaseAngle: 112.16,
    image: null,
    svsFrame: 3013,
  },
  {
    date: '2025-06-06',
    illumination: 80.1,
    phase: 'Waxing Gibbous',
    phaseAngle: 126.88,
    image: null,
    svsFrame: 3757,
  },
  {
    date: '2025-07-06',
    illumination: 82.3,
    phase: 'Waxing Gibbous',
    phaseAngle: 130.27,
    image: null,
    svsFrame: 4477,
  },
  {
    date: '2025-08-06',
    illumination: 91.2,
    phase: 'Waxing Gibbous',
    phaseAngle: 145.63,
    image: null,
    svsFrame: 5221,
  },
  {
    date: '2025-09-06',
    illumination: 97.9,
    phase: 'Waxing Gibbous',
    phaseAngle: 163.58,
    image: null,
    svsFrame: 5965,
  },
  {
    date: '2025-10-06',
    illumination: 99.4,
    phase: 'Waxing Gibbous',
    phaseAngle: 170.9,
    image: null,
    svsFrame: 6685,
  },
  {
    date: '2025-11-06',
    illumination: 98.4,
    phase: 'Waning Gibbous',
    phaseAngle: 193.53,
    image: null,
    svsFrame: 7429,
  },
  {
    date: '2025-12-06',
    illumination: 96.3,
    phase: 'Waning Gibbous',
    phaseAngle: 201.71,
    image: null,
    svsFrame: 8149,
  },
  {
    date: '2026-01-06',
    illumination: 87.8,
    phase: 'Waning Gibbous',
    phaseAngle: 221.02,
    image: null,
    svsFrame: 133,
  },
  {
    date: '2026-02-06',
    illumination: 77.8,
    phase: 'Waning Gibbous',
    phaseAngle: 236.27,
    image: null,
    svsFrame: 877,
  },
  {
    date: '2026-03-06',
    illumination: 90.5,
    phase: 'Waning Gibbous',
    phaseAngle: 215.8,
    image: null,
    svsFrame: 1549,
  },
  {
    date: '2026-04-06',
    illumination: 82.4,
    phase: 'Waning Gibbous',
    phaseAngle: 229.51,
    image: null,
    svsFrame: 2293,
  },
];
